name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_featured: Dragonlord1005/python-text-based-game-framework
          plugin_skyline: yes
          plugin_skyline_year: 2021            # Set to 0 to display current year
          plugin_skyline_frames: 60         # Use 60 frames (half-loop)
          plugin_skyline_quality: 0.5       # Set image quality
          plugin_skyline_compatibility: yes
          plugin_achievements: yes
          plugin_achievements_threshold: 6
          plugin_achievements_secrets: no
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          
