name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "30 8 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics-classic:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_featured: Dragonlord1005/python-text-based-game-framework, Dragonlord1005/discord-bot
          plugin_achievements: yes
          plugin_achievements_threshold: 6
          plugin_achievements_secrets: no
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 30        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: America/Denver
          
